version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: mediconnect-db
    environment:
      POSTGRES_DB: mediconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./mediconnect-backend
      dockerfile: Dockerfile
    container_name: mediconnect-api
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=mediconnect;Username=postgres;Password=password
      - Jwt__Key=THIS_IS_A_SUPER_SECRET_KEY_123456_FOR_DOCKER
      - Jwt__Issuer=MediConnect
      - Jwt__Audience=MediConnectUsers
      - Jwt__DurationInMinutes=60
    ports:
      - "5195:8080"

  frontend:
    build:
      context: ./mediconnect-frontend
      dockerfile: Dockerfile
    container_name: mediconnect-web
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  postgres_data:
