/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DoctorApplyRouteImport } from './routes/doctor-apply'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientMessagesRouteImport } from './routes/patient.messages'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientAssistantRouteImport } from './routes/patient.assistant'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorConversationsRouteImport } from './routes/doctor.conversations'
import { Route as DoctorCalendarRouteImport } from './routes/doctor.calendar'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor.analytics'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PatientDoctorsIdRouteImport } from './routes/patient.doctors.$id'
import { Route as PatientBookIdRouteImport } from './routes/patient.book.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorApplyRoute = DoctorApplyRouteImport.update({
  id: '/doctor-apply',
  path: '/doctor-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorConversationsRoute = DoctorConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorCalendarRoute = DoctorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PatientDoctorsIdRoute = PatientDoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientDoctorsRoute,
} as any)
const PatientBookIdRoute = PatientBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/doctor-apply': typeof DoctorApplyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/calendar': typeof DoctorCalendarRoute
  '/doctor/conversations': typeof DoctorConversationsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/book/$id': typeof PatientBookIdRoute
  '/patient/doctors/$id': typeof PatientDoctorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor-apply': typeof DoctorApplyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/calendar': typeof DoctorCalendarRoute
  '/doctor/conversations': typeof DoctorConversationsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/patient/book/$id': typeof PatientBookIdRoute
  '/patient/doctors/$id': typeof PatientDoctorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/doctor-apply': typeof DoctorApplyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/calendar': typeof DoctorCalendarRoute
  '/doctor/conversations': typeof DoctorConversationsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/book/$id': typeof PatientBookIdRoute
  '/patient/doctors/$id': typeof PatientDoctorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/doctor-apply'
    | '/forgot-password'
    | '/login'
    | '/patient'
    | '/register'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/calendar'
    | '/doctor/conversations'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/doctors'
    | '/patient/messages'
    | '/patient/settings'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/patient/book/$id'
    | '/patient/doctors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor-apply'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/calendar'
    | '/doctor/conversations'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/doctors'
    | '/patient/messages'
    | '/patient/settings'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/patient/book/$id'
    | '/patient/doctors/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/doctor-apply'
    | '/forgot-password'
    | '/login'
    | '/patient'
    | '/register'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/calendar'
    | '/doctor/conversations'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/doctors'
    | '/patient/messages'
    | '/patient/settings'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/patient/book/$id'
    | '/patient/doctors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  DoctorApplyRoute: typeof DoctorApplyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-apply': {
      id: '/doctor-apply'
      path: '/doctor-apply'
      fullPath: '/doctor-apply'
      preLoaderRoute: typeof DoctorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/conversations': {
      id: '/doctor/conversations'
      path: '/conversations'
      fullPath: '/doctor/conversations'
      preLoaderRoute: typeof DoctorConversationsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/calendar': {
      id: '/doctor/calendar'
      path: '/calendar'
      fullPath: '/doctor/calendar'
      preLoaderRoute: typeof DoctorCalendarRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/doctors/$id': {
      id: '/patient/doctors/$id'
      path: '/$id'
      fullPath: '/patient/doctors/$id'
      preLoaderRoute: typeof PatientDoctorsIdRouteImport
      parentRoute: typeof PatientDoctorsRoute
    }
    '/patient/book/$id': {
      id: '/patient/book/$id'
      path: '/book/$id'
      fullPath: '/patient/book/$id'
      preLoaderRoute: typeof PatientBookIdRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorCalendarRoute: typeof DoctorCalendarRoute
  DoctorConversationsRoute: typeof DoctorConversationsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorCalendarRoute: DoctorCalendarRoute,
  DoctorConversationsRoute: DoctorConversationsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientDoctorsRouteChildren {
  PatientDoctorsIdRoute: typeof PatientDoctorsIdRoute
}

const PatientDoctorsRouteChildren: PatientDoctorsRouteChildren = {
  PatientDoctorsIdRoute: PatientDoctorsIdRoute,
}

const PatientDoctorsRouteWithChildren = PatientDoctorsRoute._addFileChildren(
  PatientDoctorsRouteChildren,
)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientDoctorsRoute: typeof PatientDoctorsRouteWithChildren
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientBookIdRoute: typeof PatientBookIdRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientAssistantRoute: PatientAssistantRoute,
  PatientDoctorsRoute: PatientDoctorsRouteWithChildren,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientBookIdRoute: PatientBookIdRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  DoctorApplyRoute: DoctorApplyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
